services:
  mysql_db:
    image: mysql:5.7
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tododb
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopassword
    # volumes: 
    #   - mysql-data:/var/lib/mysql
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "3307:3306"

  backend:
    depends_on:
        - mysql_db
    build: ./backend
    container_name: todo-backend
    restart: always
    environment:
      DB_HOST: todo-mysql
      DB_USER: todo
      DB_PASSWORD: todopassword
      DB_NAME: tododb
      PORT: 5000
    ports: 
      - "5000:5000"
    

  frontend:
    depends_on:
      - backend
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "3000:80"
    

volumes:
  mysql-data:
